name: Vite Deploy Develop

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v2
      
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run develop
      
    - name: 📂 Sync folders and files to the server
      uses: SamKirkland/FTP-Deploy-Action@4.3.3      
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.PRO_FTP_USERNAME }}
        password: ${{ secrets.PRO_FTP_PASSWORD }}
        local-dir: ./dist/ 
        server-dir: sandboxcrm.lineaitalia.mx/front/
